server:
  port: 8080
  error:
       path: /error

#spring mvc
spring:
   mvc:
        view:
          prefix: /WEB-INF/views/
          suffix: .jsp
      #        static-path-pattern: /WEB-INF/resources/**
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     spring.datasource.druid.url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
     spring.datasource.druid.driver-class-name: com.mysql.jdbc.Driver
     spring.datasource.druid.username: root
     spring.datasource.druid.password: 123456
## 初始化大小，最小，最大
    spring.datasource.druid.initial-size: 5
    spring.datasource.druid.min-idle: 5
    spring.datasource.druid.max-active: 20
#    #配置获取连接等待超时的时间
    spring.datasource.druid.max-wait: 60000
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    time-between-eviction-runs-millis: 60000
## 配置一个连接在池中最小生存的时间，单位是毫秒
#    min-evictable-idle-time-millis: 300000
#    #检测连接是否有效的sql
#    validation-query: SELECT 'x'
#    test-on-borrow: false
#    test-while-idle: true
#    test-on-return: false
## PSCache Mysql下建议关闭
#    pool-prepared-statements: false
#    max-pool-prepared-statement-per-connection-size: -1
## 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,log4j
## 合并多个DruidDataSource的监控数据
#    use-global-data-source-stat: true
#    connection-properties: druid.stat.mergeSql: true;druid.stat.slowSqlMillis: 5000
#  使用druid #   resourc#     static-locations: classpath:webapp/WEB-INF/resource/

#pagehelper
pagehelper.helperDialect: mysql
pagehelper.reasonable: true
pagehelper.supportMethodsArguments: true
pagehelper.params: count=countSql



